<?php

/**
 * Yii app stub file. Autogenerated by yii2-stubs-generator (stubs console command).
 * Used for enhanced IDE code autocompletion.
 * Updated on 2019-06-21T13:02:17+0000
 */
class Yii extends \yii\BaseYii
{
    /**
     * @var BaseApplication|WebApplication|ConsoleApplication the application instance
     */
    public static $app;
}
/**
 * @property User $user
 * @property yii\redis\Connection $redis
 **/
abstract class BaseApplication extends yii\base\Application
{
}

class WebApplication extends yii\web\Application
{
}

class ConsoleApplication extends yii\console\Application
{
}

/**
 * Class User
 */
class User extends app\components\UserJwt
{
    /**
     * @var \app\models\User
     */
    public $identity;
}
